---
- name: System
  hosts: lab
  become: yes
  roles:
    - role: system

- name: Docker-machine
  hosts: docker
  become: yes
  roles:
    - role: docker

- name: Streaming
  hosts: infotainment
  become: yes
  roles:
    - role: jellyfin
    - role: plex
