concurrency: ci-${{ github.workflow }}-${{ github.ref }}
jobs:
  build-ansible-container:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: short-sha
        name: Get short SHA
        run: echo "tag=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN_RW }}
          username: ${{ secrets.CONTAINER_REGISTRY_USER_RW }}
      - if: ${{ github.ref != 'refs/heads/main' }}
        name: Build branch
        uses: docker/build-push-action@v5
        with:
          context: .
          file: tools/ansible/Dockerfile
          push: true
          tags: matamun/ansible:${{ steps.short-sha.outputs.tag }}
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build main
        uses: docker/build-push-action@v5
        with:
          context: .
          file: tools/ansible/Dockerfile
          push: true
          tags: matamun/ansible:${{ steps.short-sha.outputs.tag }},matamun/ansible:latest
name: Build ansible container
on:
  push:
    paths:
      - tools/ansible/Dockerfile
  workflow_dispatch: # Allow to manually trigger the pipeline
