---
concurrency: ci-${{ github.workflow }}-${{ github.ref }}
jobs:
  build-tailspin-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: short-sha
        name: Get short SHA
        run: echo "tag=$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
      - if: ${{ github.ref != 'refs/heads/main' }}
        name: Build branch
        uses: docker/build-push-action@v6
        with:
          context: .
          file: tools/tailspin/Dockerfile
          push: true
          tags: matamun/tspin:${{ steps.short-sha.outputs.tag }}
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build main
        uses: docker/build-push-action@v6
        with:
          context: .
          file: tools/tailspin/Dockerfile
          push: true
          tags: matamun/tspin:${{ steps.short-sha.outputs.tag }},matamun/tspin:latest
name: Container - tailspin
on:
  push:
    paths:
      - .github/workflows/container-tailspin.yaml
      - tools/tailspin/Dockerfile
  schedule:
    - cron: 30 7 * * 1
  workflow_dispatch: # Allow to manually trigger the pipeline
permissions: {}
