---
jobs:
  dependabot-auto-merge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - id: metadata
        name: Dependabot metadata
        uses: dependabot/fetch-metadata@v2.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --rebase "$PR_URL"
name: Dependabot - auto-merge
on: pull_request
permissions:
  contents: write
  pull-requests: write
