jobs:
  delete-workflow-runs:
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          keep_minimum_runs: 1
          repository: ${{ github.repository }}
          retain_days: 7
          token: ${{ github.token }}
name: GHA - delete workflow runs
on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:
permissions: {}
